---
version: "3"
services:
  app:
    build:
      context: ./app
    ports:
      - 5000:5000
    volumes:
      - ./app/my_database.json:/app/my_database.json
    environment:
      DATABASE_URL: persistentdb:///my_database.json
    networks:
      - custom_network
  data_generator:
    build:
      context: ./data_generator
    networks:
      - custom_network
networks:
  custom_network:
    driver: bridge
volumes:
  my_volume: null
